# The Problem
<!-- 
Outlining the issue / weak point / problem to be solved by this proposal. This should be a compelling section that sets the reader up for the next section - the proposed solution!

It is important to cover:

 - [ ] What the problem is
 - [ ] Who it affects
 - [ ] Have there been previous attempts to resolve the problem
 - [ ] Why it should be tackled
-->
Tech conferences are a vital way of growing the community, especially when the conferences are organised by people from within the community. Like user groups, they provide an essential mechanism for people to network, learn, and develop themselves. Conferences can cover a higher volume and broader scope of content than a user group can. This makes them applicable to people from different industries with varying levels of knowledge around a technology - the ability to cater for this variety is where they can provide a substantial benefit over and above a user group.

In 2015, we saw a bumper number of R conferences. These were:

- General R
    + UseR!, Denmark, ~£400
    + EARL London, UK, ~£400
    + EARL Boston, USA, ~£400
    + Rencontres R, France, ~£120
    + Xian R, China, ~£120
    + Beijing R, China, ~£110
    + New York R conference, USA, ~£350
    + R-omania conference, Romania, ~£75
    + VII Jornadas de Usuarios de R (7th Meeting of Spanish R Users), Spain, **FREE**
- BioConductor
    + BioC 2015, USA, ~£400
    + European BioConductor Developers' Meeting 2015, Germany, **FREE**
    + European BioConductor Developers' Meeting 2015, UK, **FREE**
    + BioConductor Asia-Pacific Developer Meeting, Japan, **FREE**
- Industry specific
    + R/Finance, USA, ~£200
    + R in Insurance, Holland, ~£300
    + Psychoco 2015, Holland, **FREE**
    + R Programing Language and Basic Statistics for Research (R2015), Thailand, ~£100

Unfortunately, this is still relatively few conferences. R has a huge surface area and the industry/topic specific conferences make a lot of sense. General conferences though enable a broad audience to come together to learn, giving important benefits around the cross-pollination of ideas. Of these conferences though, they occured in just seven countries around the world last year.

The BioConductor events are typically free but most other R conferences are not. Between the admission costs and the travel costs to reach the relatively few conferences, it puts R conferences out of reach for much of the world. Even in countries where they take place, many people won't be able to get the budget or sign off to attend. As a result, R conferences have an inherently biased audience and they do not help foster the growth of the R community enough.

Additionally, the limited options do not help us foster local speakers and organisers. Community driven conferences allow for a stronger focus of developing the R ecosystem so that we can help sustain an increasing number of experts and community leaders. These people are essential in facilitating a wider growth in the R user base.
