# The proposal
<!--
This is where the proposal should be outlined. 
-->

<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->
Individual conferences take a long time to get off the ground. It's an uphill battle to establish an identity, a platform, and an adequate pool of speakers and sponsors. This proposal seeks to address these difficulties by:

  1. Providing a brand for R community conferences that can be used by R user groups globally to hold conferences in their region
  2. Developing a central site for the hosting and management of the conferences, using and contributing to an existing open-source conference system initiative
  3. Holding three trial conferences in the US, EMEA, and another region

This delivers a much needed mechanism for the growth of R conferences globally.

<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->
## The brand: satRdays
```{r fig.width=2, fig.height=2,echo=FALSE, warning=FALSE}
library(png)
library(grid)
img <- readPNG("../satRdayLogo.png")
 grid.raster(img)
```

satRdays will be free or cheap conferences held primarily on Saturdays. They will focus on R but the emphasis will be determined by local audience. A satRday will typically be run by one or more user group organisers looking to provide a regional conference.

satRdays are held on weekends to make it easier for people who cannot take the time out of the week to attend, or those who have to travel to the event (like speakers). The maximum cost of £30 per head makes the event much more accessible, and provisions will be put in place to enable free attendance for those that need it.

The specific format of a satRday is up to the individual organisers but it will typically be "standard conference" shaped, with multiple sessions happening simultaneously.

satRdays are community events, so everyone including the speakers will be volunteers.
 
## The infrastructure: satRdays.org
There will be a central site which is used by satRday organisers to host and manage their conferences. The site will facilitate the:

- Creation of events with templated content
- Customisation of event content by organisers
- Submission of sessions by speakers for consideration
- Selection and scheduling of sessions by organisers
- Registration of attendees
- Hosting of slides etc. from sessions

There are number of open source conference systems out there, and these were evaluated on the following factors:

- How many initial requirements were possible out of the box
- The state of the OS project
- The ability of the proposal participants to extend the system

A Drupal site based on the Conference Organiser Distribution will be used.

## The conferences
There will be three trial conferences in 2016. These will be used to understand factors like existing appetite, speaker availability, optimal session formats, and sponsor appetite. The conferences are anticipated to be held in 2016H2.

The three conferences will be part funded by the R Consortium and the Consortium members can be listed as individual companies for increased brand awareness. They may also charge up to £30 per attendee to cover the rest of the costs.