# Requirements
<!-- 
An idea of what is required to make the project actually happen
-->

## People
<!--
Who needs to be involved, what's the proposed structure, what will it take to get their involvement?
-->
### Central
The infrastructure and brand need some central coordination. Steph Locke will develop the central facilities, and grow the contributors to this area.

### Conferences
Organisers are needed for the three conferences. Gergely Daróczi is our first organiser and will put together a team for his conference.

## Processes
<!-- 
What processes need to be put in place e.g. codes of conduct, regular ISC meetings, handover to the community at large?
-->
There is a fundamental emphasis on open source within the satRday project. As little as possible will be closed source, and the community at large will be able to contribute to the development. With this in mind, not only will a code of conduct apply to the conferences themselves, but a contributor code of conduct will also apply.

The IP and assets like the satRdays.org domain will need to be transferred to ownership by the R Consortium.

How the financing of the events occurs will also need to be addressed in collaboration with the Consortium. These events are intended to be not for profit so an event organiser should aim for break-even, and to ensure that the Consortium is not left with a big bill, liability for an event will need to sit with individual organisers in some fashion. A rough process for this could be:

  1. Organisers deliver an initial budget for their event
  2. Funds get allocated from the pool to contribute towards venue & catering costs and are used to **directly** pay or part pay those costs
  3. Other funds go to the organiser's nominated accounts and will be used by them to handle any other costs
  4. Post-event organisers deliver provide a budget vs actual report
  5. Excess funds go back to the Consortium

## Tools & Tech
<!--
What is going to be needed to deliver this project? 

Will cloud computing be used - if yes are there are necessary components that will be deciding factors between providers?

Are there tools or tech that don't exist that will be produced to facilitate the project?
-->
  - The OS conference system: [Conference Organizing Distribution](http://usecod.com/)
  - Site hosting
  
  
## Funding
<!-- 
[TO DO] THE GUIDANCE IS PRETTY UNCLEAR, ESP IN LIGHT OF GABOR'S PROPOSAL VS AWARD SIZE

-->
### Central infrastructure
The central site will need hosting. Hosting of the site is expected to cost ~£50 per month.

### Conferences
The trial conferences are expected to have ~600 people attend in total.  The requested amount of monetary support for these events is £9,000. This will make the R Consortium (and it's individual members) main sponsors for the events. The gap between that and estimated cost per delegate of £25-£35 would then be made from either additional sponsors or from small fees to attendees. 

## Summary
<!--
A summary of the requirements that contextualises the costs
-->
  - On-going hosting costs of <£600 per year
  - Initial support of £9,000