# Signatories
<!-- 
This section provides the ISC with a view of the support received from the community for a proposal. Acceptance isn't predicated on popularity but community acceptance is important.  Willingness to accept outside input is also a good marker for project delivery. 

An optional section would be for R-Core signatories where changes to R are proposed.
-->

## Project team

### Steph Locke
Steph's a Principal Consultant at Mango Solutions and runs user groups & conferences in her spare time. She runs R, SQL, and .Net user groups in Cardiff, UK, and organises national conferences called SQL Relay. Over the past 3 years she's organised 25 days of SQL Relay conferences in more than 12 locations. Most recently, Microsoft made her a Data Platform Most Valued Professional for her community work in and around SQL Server and R.

### Gergely Daroczi

## Interested parties
We've had tremendous support from the community over the length of developing the proposal. From the first comments on the [initial blog post](http://itsalocke.com/sqlsaturdays-but-for-r/), to active discussion on the [repository](https://github.com/stephlocke/RSaturday-proposal), to people signing up as interested parties towards the end of the proposal development cycle. Below is a breakdown of the interested parties:

```{r, echo = FALSE, fig.width = 6, fig.height = 3}

## load anonymized data from Google Spreadsheet
## NOTE this is a manual "copy and paste" (!) of the survey responses
##      into a new spreadsheet, as there is no other way to clear
##      the e-mail addresses from the revision history
library(googlesheets)
responses <- gs_key('1bkHGoae_j3Ikp3Bw7AO9kxCu_tC2HSzGhvlSMskGHvI', visibility = 'public', verbose = FALSE)
responses <- gs_read(responses, ws = 1, range = cell_rows(1:279), verbose = FALSE)

## data.table showcase
library(data.table)
responses <- data.table(responses)

## programmer-friendly column names
setnames(responses, c('region', 'location', 'travel', 'roles'))

## number of interested parties per continent
suppressPackageStartupMessages(library(ggplot2))
ggplot(responses, aes(x = region)) +
  geom_bar() + theme_bw() + coord_flip() +
  geom_text(stat = 'bin', aes(y = ..count.. , label = ..count..),
            color = 'white', hjust = 1.1) +
  xlab('') + ylab('') + ggtitle('Number of interested parties per region')

```
